# Generated by Django 4.0.3 on 2022-03-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grina', '0002_data_course_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='img_uri',
            field=models.URLField(default=123),
            preserve_default=False,
        ),
    ]
