# Generated by Django 4.0.3 on 2022-03-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grina', '0003_data_img_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
