# Generated by Django 4.0.3 on 2022-03-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grina', '0005_subcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='sub_courses',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='grina.subcourse'),
            preserve_default=False,
        ),
    ]
