# Generated by Django 4.0.3 on 2022-03-30 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grina', '0006_data_sub_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('correct', models.BooleanField()),
                ('choice_index', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='subcourse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='VideoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('poster', models.URLField()),
                ('tip', models.CharField(max_length=200)),
                ('server_choice_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc1', to='grina.serverchoice')),
                ('server_choice_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc2', to='grina.serverchoice')),
                ('server_choice_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc3', to='grina.serverchoice')),
                ('server_choice_4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc4', to='grina.serverchoice')),
            ],
        ),
    ]
