# Generated by Django 4.0.3 on 2022-03-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grina', '0007_serverchoice_alter_subcourse_id_videotest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videotest',
            old_name='image',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='videotest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
