# Generated by Django 4.0.3 on 2022-03-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grina', '0009_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='data',
        ),
        migrations.AddField(
            model_name='course',
            name='data',
            field=models.ManyToManyField(to='grina.data'),
        ),
        migrations.RemoveField(
            model_name='data',
            name='sub_courses',
        ),
        migrations.AddField(
            model_name='data',
            name='sub_courses',
            field=models.ManyToManyField(to='grina.subcourse'),
        ),
    ]
