# Generated by Django 4.0.3 on 2022-03-31 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grina', '0010_remove_course_data_course_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='data',
        ),
        migrations.AddField(
            model_name='course',
            name='data',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='grina.data'),
            preserve_default=False,
        ),
    ]
