# Generated by Django 4.0.4 on 2022-05-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grina', '0011_remove_course_data_course_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='data',
        ),
        migrations.AddField(
            model_name='course',
            name='data',
            field=models.ManyToManyField(blank=True, to='grina.data'),
        ),
        migrations.AlterField(
            model_name='videotest',
            name='source',
            field=models.FileField(upload_to='grinavideos'),
        ),
    ]
