# Generated by Django 4.0.4 on 2022-05-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grina', '0012_remove_course_data_course_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='id',
            field=models.CharField(max_length=1000000, primary_key=True, serialize=False),
        ),
    ]
