# Generated by Django 4.0.4 on 2022-05-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grina', '0014_alter_data_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTestStack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('videotests', models.ManyToManyField(blank=True, to='grina.videotest')),
            ],
        ),
    ]
