# Generated by Django 4.0.4 on 2022-05-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grina', '0016_videocard_videocardstack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcourse',
            old_name='api_link',
            new_name='api_link_cards',
        ),
        migrations.AddField(
            model_name='subcourse',
            name='api_link_tests',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
