# Generated by Django 4.1 on 2022-09-07 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grina', '0017_rename_api_link_subcourse_api_link_cards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.FileField(upload_to='grinavideos')),
                ('tip', models.CharField(max_length=200)),
                ('eng_text', models.CharField(max_length=200)),
                ('ru_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='videocardstack',
            name='videocards',
        ),
        migrations.RemoveField(
            model_name='videotest',
            name='server_choice_1',
        ),
        migrations.RemoveField(
            model_name='videotest',
            name='server_choice_2',
        ),
        migrations.RemoveField(
            model_name='videotest',
            name='server_choice_3',
        ),
        migrations.RemoveField(
            model_name='videotest',
            name='server_choice_4',
        ),
        migrations.RemoveField(
            model_name='videoteststack',
            name='videotests',
        ),
        migrations.RemoveField(
            model_name='serverchoice',
            name='choice_index',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.DeleteModel(
            name='VideoCard',
        ),
        migrations.DeleteModel(
            name='VideoCardStack',
        ),
        migrations.DeleteModel(
            name='VideoTest',
        ),
        migrations.DeleteModel(
            name='VideoTestStack',
        ),
        migrations.AddField(
            model_name='videoobject',
            name='server_choice_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc1', to='grina.serverchoice'),
        ),
        migrations.AddField(
            model_name='videoobject',
            name='server_choice_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc2', to='grina.serverchoice'),
        ),
        migrations.AddField(
            model_name='videoobject',
            name='server_choice_3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc3', to='grina.serverchoice'),
        ),
        migrations.AddField(
            model_name='videoobject',
            name='server_choice_4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sc4', to='grina.serverchoice'),
        ),
    ]
