# Generated by Django 4.1 on 2022-09-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grina', '0018_videoobject_remove_videocardstack_videocards_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcourse',
            old_name='api_link_cards',
            new_name='api_link',
        ),
        migrations.RemoveField(
            model_name='subcourse',
            name='api_link_tests',
        ),
    ]
