# Generated by Django 4.1 on 2022-09-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grina', '0020_craftstack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftstack',
            name='video_objects',
            field=models.ManyToManyField(blank=True, to='grina.videoobject'),
        ),
    ]
